### ISSUE TITLE
Eroor: Path and scoreboard with games are required

### ISSUE THREAD

**Issue by spacecowboyian** [jaw187/mlbplays#2]
Just started getting this error. Is it me?

**Comment by jaw187** [comment]
https://github.com/jaw187/mlbplays/blob/master/lib/mlb.js#L50 Will throw that error.  The code isn't new, but the scoreboard is a result of grabbing data from MLB, something probably changed there.

**Comment by jaw187** [comment]
By chance was there a particular day that is throwing the error?

**Comment by spacecowboyian** [comment]
My script searches for the current day... Ooooohh. I wonder if I'm not adding a lead zero where one belongs for the day.. this all started after the start of the new month. Sadly I can't test new code for a few more days.

**Comment by jaw187** [comment]
Def need the leading zeros, that could be the problem.  https://github.com/jaw187/mlbplays/blob/master/test/mlb.js#L50-L52

**Comment by jaw187** [comment]
@spacecowboyian is this an issue?

**Comment by spacecowboyian** [comment]
Nope. Sorry. Was on vacation and forgot to close it :) Thanks!
